### ISSUE TITLE
Plugin system for GQLgen

### ISSUE THREAD

**Issue by ghost** [samlitowitz/graphqlc#1]
This is also something i think is really useful.

DO you have a roadmap or thoughts on one so i can see where i can help.

**Comment by samlitowitz** [comment]
Internally graphqlc could use testing, documentation, optimization, and general code hygiene. Type extension support depends on resolution of this [issue](https://github.com/graphql-go/graphql/issues/481).

Big ticket external items are comprehensive code generators (data structures for GraphQL types, resolver and server boilerplate, language/framework specific boilerplate) for popular languages/frameworks, e.g. Go, Java, PHP, protobuf, or gRPC.

The gqlgen generator is a stop-gap so developers can migrate to graphqlc without a hitch. Long term, a better pattern of generation for Go should probably be developed to take advantage of things like insertion points to allow follow-on code generators to generate code for resolvers, or add middleware to the server without having to do modifications by hand.

@gedw99
